"""create campaign requests

Revision ID: 5b5a1cfb9f01
Revises: e7a3c2d9f0b1
Create Date: 2026-01-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b5a1cfb9f01"
down_revision = "e7a3c2d9f0b1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("advertiser_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column("budget_usdt", sa.Numeric(18, 2), nullable=True),
        sa.Column("budget_ton", sa.Numeric(18, 2), nullable=True),
        sa.Column("preferred_language", sa.String(), nullable=True),
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("min_subscribers", sa.Integer(), nullable=True),
        sa.Column("min_avg_views", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["advertiser_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaign_requests_advertiser_id"), "campaign_requests", ["advertiser_id"], unique=False)
    op.create_index(op.f("ix_campaign_requests_is_active"), "campaign_requests", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaign_requests_is_active"), table_name="campaign_requests")
    op.drop_index(op.f("ix_campaign_requests_advertiser_id"), table_name="campaign_requests")
    op.drop_table("campaign_requests")
    # ### end Alembic commands ###
