"""create campaign applications

Revision ID: 8a7d3f1c2b4e
Revises: 5b5a1cfb9f01
Create Date: 2026-01-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a7d3f1c2b4e"
down_revision = "5b5a1cfb9f01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("proposed_format_label", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), server_default=sa.text("'submitted'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign_requests.id"]),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"]),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "channel_id", name="ux_campaign_applications_campaign_channel"),
    )
    op.create_index(op.f("ix_campaign_applications_campaign_id"), "campaign_applications", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_campaign_applications_channel_id"), "campaign_applications", ["channel_id"], unique=False)
    op.create_index(op.f("ix_campaign_applications_owner_id"), "campaign_applications", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaign_applications_owner_id"), table_name="campaign_applications")
    op.drop_index(op.f("ix_campaign_applications_channel_id"), table_name="campaign_applications")
    op.drop_index(op.f("ix_campaign_applications_campaign_id"), table_name="campaign_applications")
    op.drop_table("campaign_applications")
    # ### end Alembic commands ###
