"""create deals

Revision ID: b3c7e1f2a9d8
Revises: 8a7d3f1c2b4e
Create Date: 2026-01-31 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3c7e1f2a9d8"
down_revision = "8a7d3f1c2b4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("advertiser_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("channel_owner_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=True),
        sa.Column("listing_format_id", sa.Integer(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("campaign_application_id", sa.Integer(), nullable=True),
        sa.Column("price_ton", sa.Numeric(18, 2), nullable=False),
        sa.Column("ad_type", sa.String(), nullable=False),
        sa.Column("creative_text", sa.Text(), nullable=False),
        sa.Column("creative_media_type", sa.String(), nullable=False),
        sa.Column("creative_media_ref", sa.String(), nullable=False),
        sa.Column("posting_params", sa.JSON(), nullable=True),
        sa.Column("state", sa.String(), server_default=sa.text("'DRAFT'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source_type = 'listing' AND listing_id IS NOT NULL AND listing_format_id IS NOT NULL "
            "AND campaign_id IS NULL AND campaign_application_id IS NULL) OR "
            "(source_type = 'campaign' AND campaign_id IS NOT NULL AND campaign_application_id IS NOT NULL "
            "AND listing_id IS NULL AND listing_format_id IS NULL)",
            name="ck_deals_source",
        ),
        sa.ForeignKeyConstraint(["advertiser_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["campaign_application_id"], ["campaign_applications.id"]),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign_requests.id"]),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"]),
        sa.ForeignKeyConstraint(["channel_owner_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["listing_format_id"], ["listing_formats.id"]),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_application_id", name="ux_deals_campaign_application_id"),
        sa.UniqueConstraint("campaign_id", name="ux_deals_campaign_id"),
    )
    op.create_index(op.f("ix_deals_advertiser_id"), "deals", ["advertiser_id"], unique=False)
    op.create_index(op.f("ix_deals_channel_id"), "deals", ["channel_id"], unique=False)
    op.create_index(op.f("ix_deals_state"), "deals", ["state"], unique=False)
    op.create_table(
        "deal_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("from_state", sa.String(), nullable=True),
        sa.Column("to_state", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deal_events_created_at"), "deal_events", ["created_at"], unique=False)
    op.create_index(op.f("ix_deal_events_deal_id"), "deal_events", ["deal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deal_events_deal_id"), table_name="deal_events")
    op.drop_index(op.f("ix_deal_events_created_at"), table_name="deal_events")
    op.drop_table("deal_events")
    op.drop_index(op.f("ix_deals_state"), table_name="deals")
    op.drop_index(op.f("ix_deals_channel_id"), table_name="deals")
    op.drop_index(op.f("ix_deals_advertiser_id"), table_name="deals")
    op.drop_table("deals")
    # ### end Alembic commands ###
