"""create deal message selections

Revision ID: c4a8f1d9e7b2
Revises: b3c7e1f2a9d8
Create Date: 2026-01-31 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c4a8f1d9e7b2"
down_revision = "b3c7e1f2a9d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deal_message_selections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deal_id", sa.Integer(), nullable=False),
        sa.Column(
            "selected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["deal_id"], ["deals.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="ux_deal_message_selections_user"),
    )
    op.create_index(
        op.f("ix_deal_message_selections_deal_id"),
        "deal_message_selections",
        ["deal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deal_message_selections_user_id"),
        "deal_message_selections",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deal_message_selections_user_id"), table_name="deal_message_selections")
    op.drop_index(op.f("ix_deal_message_selections_deal_id"), table_name="deal_message_selections")
    op.drop_table("deal_message_selections")
    # ### end Alembic commands ###
