"""create channel stats snapshots

Revision ID: d4c9f54a8b7d
Revises: 67116531bdd4
Create Date: 2026-01-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d4c9f54a8b7d"
down_revision = "67116531bdd4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel_stats_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("subscribers", sa.Integer(), nullable=True),
        sa.Column("avg_views", sa.Integer(), nullable=True),
        sa.Column("language_stats", sa.JSON(), nullable=True),
        sa.Column("premium_stats", sa.JSON(), nullable=True),
        sa.Column("raw_stats", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_stats_snapshots_channel_id"),
        "channel_stats_snapshots",
        ["channel_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channel_stats_snapshots_channel_id"), table_name="channel_stats_snapshots")
    op.drop_table("channel_stats_snapshots")
    # ### end Alembic commands ###
